non_speakers_colon = {
            'And one personal note', 
            'Another issue in this campaign', 
            'Now to the candidates', 
            'The threats we face', 
            'I close on this', 
            'Invest and grow', 
            'One other point', 
            'But I repeat again', 
            'My message to our troops is', 
            'They have a plan for Iraq too', 
            'Nuclear power', 
            "Let's meet the candidates", 
            'Health care', 
            'Now, flip-flops', 
            "Now I'm back to square one", 
            'But I do know one thing', 
            'And I can tell you this', 
            'Tonight I say to the President', 
            "It's true", 
            "But I'll tell you this", 
            'Step one', 
            'My question is this', 
            'He talks about a grand idea', 
            'This is my point tonight', 
            'One final point', 
            'Unknown Male', 
            'I can say this', 
            'And I asked him', 
            "Let's face up to it, Dan", 
            "Here's what I believe", 
            'I want to state this', 
            'Honor, duty, and country', 
            'Myquestion to you is', 
            'The rules', 
            'So the question is', 
            'And so, you know, my position', 
            'And that is', 
            'And he asked the third one', 
            'And we have other provisions', 
            'Some other rules', 
            "Here's what's happened", 
            'I have a message for them', 
            "Here's the truth", 
            'He said', 
            'Now, the question is', 
            'We stood up and said', 
            'Ask yourself this question', 
            'Now, I can tell you this', 
            'I will make a flat statement', 
            'I repeat', 
            'Mr. Perot. Step one', 
            'Similarly, in Central America', 
            'He says', 
            'We need to make real reforms', 
            'But I would just say this', 
            "I'll close on this point", 
            'From CNN.com', 
            'But I can say this', 
            'What we do know is this', 
            'My question', 
            'I said', 
            'President Bush. Two things', 
            'Let me tell you', 
            'Ours is a good plan', 
            'And he asked the second one', 
            'But I will say this', 
            'But I can tell you this', 
            'The measurement is not',
            'PARTICIPANTS',
            'MODERATOR',
            'MODERATORS'
        }

titles = {
    'MR',
    'MS',
    'MRS'
}

non_speakers_period = {
    "Next thing",
    "That's a mistake",
    'My question to you is',
    "China-U",
    "Medicare is different",
    " Hume",
    "Not this President",
    "Smiley",
    "Now, neighborhood schools",
    "God bless",
    "This is America",
    "Thank you",
    "It's fascinating",
    "Future U",
    "Ed",
    "You bet",
    "There's a difference",
    "U",
    "Now, leadership",
    "Thank you, sir",
    "My question to you is",
    "Excuse me, Carole",
    "One final point",
    "Mr Perot?",
    "Tumulty",
    "Gentlemen, again, welcome",
    "He's proposed $2",
    "THE",
    "Kilgore",
    "Support for U",
    "Gentlemen, good evening",
    "I—let me finish",
    "First, Mr President",
    "This side",
    "We are helping",
}