non_speakers_colon = {
            'And one personal note', 
            'Another issue in this campaign', 
            'Now to the candidates', 
            'The threats we face', 
            'I close on this', 
            'Invest and grow', 
            'One other point', 
            'But I repeat again', 
            'My message to our troops is', 
            'They have a plan for Iraq too', 
            'Nuclear power', 
            "Let's meet the candidates", 
            'Health care', 
            'Now, flip-flops', 
            "Now I'm back to square one", 
            'But I do know one thing', 
            'And I can tell you this', 
            'Tonight I say to the President', 
            "It's true", 
            "But I'll tell you this", 
            'Step one', 
            'My question is this', 
            'He talks about a grand idea', 
            'This is my point tonight', 
            'One final point', 
            'Unknown Male', 
            'I can say this', 
            'And I asked him', 
            "Let's face up to it, Dan", 
            "Here's what I believe", 
            'I want to state this', 
            'Honor, duty, and country', 
            'Myquestion to you is', 
            'The rules', 
            'So the question is', 
            'And so, you know, my position', 
            'And that is', 
            'And he asked the third one', 
            'And we have other provisions', 
            'Some other rules', 
            "Here's what's happened", 
            'I have a message for them', 
            "Here's the truth", 
            'He said', 
            'Now, the question is', 
            'We stood up and said', 
            'Ask yourself this question', 
            'Now, I can tell you this', 
            'I will make a flat statement', 
            'I repeat', 
            'Mr. Perot. Step one', 
            'Similarly, in Central America', 
            'He says', 
            'We need to make real reforms', 
            'But I would just say this', 
            "I'll close on this point", 
            'From CNN.com', 
            'But I can say this', 
            'What we do know is this', 
            'My question', 
            'I said', 
            'President Bush. Two things', 
            'Let me tell you', 
            'Ours is a good plan', 
            'And he asked the second one', 
            'But I will say this', 
            'But I can tell you this', 
            'The measurement is not',
            "I offer a new direction",
            "Then the question is",
            "My question to you is",
            "[Videotape, December 16, 1999]",
            "[Unsolicited question",
            "A reminder",
            "Let me just make it clear",
}

titles = {
    'MR',
    'MS',
    'MRS',
}

non_speakers_period = {
    "Next thing",
    "That's a mistake",
    'My question to you is',
    "China-U",
    "Medicare is different",
    " Hume",
    "Not this President",
    "Smiley",
    "Now, neighborhood schools",
    "God bless",
    "This is America",
    "Thank you",
    "It's fascinating",
    "Future U",
    "Ed",
    "You bet",
    "There's a difference",
    "U",
    "Now, leadership",
    "Thank you, sir",
    "My question to you is",
    "Excuse me, Carole",
    "One final point",
    "Mr Perot?",
    "Tumulty",
    "Gentlemen, again, welcome",
    "He's proposed $2",
    "THE",
    "Kilgore",
    "Support for U",
    "Gentlemen, good evening",
    "I—let me finish",
    "First, Mr President",
    "This side",
    "We are helping",
    "Period",
    "These are inconsistencies",
    "I'm Carole Simpson",
    "I identified $6",
    "We proliferate laws",
    "I'm an outsider",
    "That's a disgrace",
    "I understand you",
    "Thank you, George",
    "Mr Bauer?",
    "There are differences",
    "I'm an outsider",
    "Two things",
    "I thank you",
    "That's the issue",
    "By the way",
    "Wait a minute",
    "Here's the question",
    "And thank you",
    "And Gary Bauer",
    "It's two-part question",
    "They need it",
    "Or Your Highness",
    "That's number one",
    "I — I",
    "Excuse me",
    "Don't go away",
    "Good evening",
    "It's been marvelous",
    "And St",
    "So St",
    "We spend $1",
    "He's my friend",
    "I've done that",
    "Go ahead, ma'am",
    "But go ahead",
    "Go ahead",
    "Mr Vice President",
    "Senator Bradley",
    "And remember this",
    "Politics is different",
    "We basically agree",
    "Both of those",
    "I'm Bernard Shaw",
    "Stand up",
    "I misspoke",
    "Please respect that",
    "He said: Holidays",
    "Second of all",
    "Stay with us",
    "Peter, you start",
    "Tom, I'm sorry",
    "Second, find opportunities",
    "I took responsibility",
    "Ask the U",
    "They want answers",
    "America spends $1",
    "When the U",
    "Thank you, Gwen",
    "The Census Bureau",
    "It's working",
    "It's not true",
    "It's a mistake",
    "Senator",
    "None here",
    "Mr Vice President?",
    "The first",
    "Now ambassador Keyes",
    "It is",
}